return {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPre", "BufNewFile" },
    build = ":TSUpdate",
    dependencies = {
      "windwp/nvim-ts-autotag",
    },
    config = function()
      local treesitter = require("nvim-treesitter.configs")
  
      treesitter.setup({
        highlight = {
          enable = true,
        },
        indent = { enable = true },
        autotag = {
          enable = true,
        },
        ensure_installed = {
          "asm",
          "bash",
          "bicep",
          "c",
          "c_sharp",
          "cmake",
          "cpp",
          "css",
          "csv",
          "diff",
          "dockerfile",
          "editorconfig",
          "fish",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "gpg",
          "graphql",
          "helm", 
          "html",
          "http",
          "ini",
          "java",
          "javascript",
          "jq",
          "jsdoc",
          "json",
          "kotlin",
          "lua",
          "make",
          "markdown",
          "markdown_inline",
          "passwd",
          "powershell",
          "regex",
          "ruby",
          "rust",
          "scss",
          "sql",
          "ssh_config",
          "tsx",
          "typescript",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
        },
        incremental_selection = {
          enable = true,
          keymaps = {
            init_selection = "<C-space>",
            node_incremental = "<C-space>",
            scope_incremental = false,
            node_decremental = "<bs>",
          },
        },
      })
    end,
  }
  